<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>资源(POS机)系统-百动网</title>
    <link href="/css/admin/wrap.css" type="text/css" rel="stylesheet" />
    <link href="/css/admin/common.css" type="text/css" rel="stylesheet">
    <script src="/js/jquery.js"></script>

    <style type="text/css">
        .snavcom_div{ display:none}
        *{margin:0; padding:0}
        body, html{ height:100%; width:100%; overflow:hidden;} /*这个高度很重要*/
        #mainTable{padding:0px;margin:0px;}
        #mainTable td,#mainTable th{padding:0px;margin:0px;}
    </style>
</head>
<body style="padding:0px;margin:0px;">