<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>操作成功-资源(POS机)管理</title>
<link href="/css/admin/wrap.css" type="text/css" rel="stylesheet" />
<link href="/css/admin/common.css" type="text/css" rel="stylesheet">
</head>

<body>
<div class="pwis">
    <div class="sucu ">
        <div class="x" style="display:none"></div>
        <h4>操作提示</h4>
        <div class="msg_box">
            <p class="msg_title"><?php echo $msg; ?></p>
            <p>
                <a href="<?php
                    if($url == '')
                        echo 'javascript:history.go(-1)';
                    else
                        echo $url;
                    ?>" style="color:#4f6b72; text-decoration:none">正在跳转,请稍后...</a>
            </p>
    </div>
    </div>
    <?php
        if($url == '')
            echo '<script language="javascript">setTimeout(function(){history.go(-1);},'.$delay.');</script>';
        else
            echo '<script language="javascript">setTimeout(function(){window.location.href="'.$url.'"}, '.$delay.');</script>';
    ?>
</div>
</body>
</html>

		