<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>资源(pos机)-百动网</title>

    <script language="javascript" src="/js/jquery.js"></script>
    <link href="/css/common.css" type="text/css" rel="stylesheet" />
    <link href="/css/login.css" type="text/css" rel="stylesheet" />
    </head>

        <body onload="$('#username').focus();">
    <form action="" method="post">
    <div class="login">
    <div class="balogo">百动网-资源(pos机)管理</div>
    <div class="boginbox">
    <dl><dt>用户名</dt><dd><input class="inpw130" id="username" name="set[username]" type="text" maxlength="30"  style="height:18px;line-height: 18px;"/></dd></dl>
    <dl><dt>密&nbsp;&nbsp;码</dt><dd><input class="inpw130"  name="set[password]" type="password" maxlength="30" style="height:18px;line-height: 18px;"/></dd></dl>
    <!--<dl><dt>验证码</dt><dd><input class="inpw60" style="_width:60px;" name="" type="text" /></dd><dd><span><img src="{staticurl action="admin/j_08.gif"}" /></span></dd></dl>-->
    <div class="loginbnt"><div class="lbng">
    <input   value=" 登 录 " type="submit" style="float:left;width:60px;margin-right:10px;"  />
    <div style="  float:left;color:#fff;width:60px;margin-top:4px;height:20px;line-height:17px"><input type="checkbox" name="set[remember]" checked="checked" value="1" style="vertical-align:bottom" >记住我</div>

    </div></div>
    </div>
    </div></form>
    </body>
    </html>
